version: '2.2'

services:
  python:
    build: .
    command: "python3 app.py"
    links:
      - mongodb
      - neo4j

  mongodb:
    image: mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      MONGO_INITDB_ROOT_USERNAME: antoine
      MONGO_INITDB_ROOT_PASSWORD: kylian
      MONGODB_DATABASE: my_db

  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/kylian
